config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'log_out' => "sessions#destroy", :as => "log_out"
  get 'log_in' => "sessions#new", :as => "log_in"
  get 'sign_up' => "users#new", :as => "sign_up"
  
    
  resources :lists do
    resources :items
  end
  
  resources :users
  resources :sessions
  
  get ":username" => "users#show"
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
  
  validates :list_name, presence: true
  
  accepts_nested_attributes_for :items, reject_if: lambda{ |a| a[:name].blank? }, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  
  attr_accessor :password
  
  before_save :encrypt_password
  after_save :clear_password
  
  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, format: EMAIL_REGEX  #, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..15 }, on: :create
  validates :password_confirmation, presence: true


  def self.authenticate(username, password)
    user = find_by username: username
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
     user 
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def clear_password              # is this necessary?
    self.password = nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  private 
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      redirect_to log_in_path
    end
  end
  
  def save_login_state
   if session[:user_id]
     redirect_to "/#{current_user.username}"
     # redirect_to user_path(current_user.id) - WORKS
   end
  end
  
  def permitted_list
    if List.find(params[:id]).user_id != current_user.id
      redirect_to user_path(current_user)
      flash[:notice] = "You can only access your own content"
    end
  end
  
  # def permitted_user
  #  if User.find(params[:id]) != current_user
  #    redirect_to user_path(current_user)
  #    flash[:notice] = "This is not your user"
  #  end
  # end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_action :permitted_list, only: [:show]

  def index
    #@garbage = current_user.lists.all      
  end
  
  def show
    @list = List.includes(:items).find(params[:id])
  end
  
  def new
    @list = List.new
    1.times { @list.items.build }
  end
  
  def create
    @list = List.create(list_params)
        
    if @list.save
      redirect_to "/#{@list.user.username}", notice: "#{@list.list_name.capitalize} was created!"
    else
      1.times{ @list.items.build }
      flash.now.alert = "Your list must have a name"
      render :edit
    end
    
  end
  
  def edit
    @list = List.find(params[:id])
    1.times { @list.items.build }
  end
  
  def update
    @list = List.find(params[:id])
        
    if params[:commit] == "Email List!"
      SendList.quick_send(@list, params[:send_to_address], params[:sender]).deliver
      redirect_to @list, notice: "Email was sent to #{params[:send_to_address]}"
    elsif @list.update(list_params)
      redirect_to @list, notice: "List Updated!"
    else
      render 'form'
    end
      
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    
    redirect_to "/#{@list.user.username}"
  end


  private
  def list_params
    params.require(:list).permit(:list_name, :notes, :user_id, items_attributes: [:id, :name, :quan, :notes, :_destroy])
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  before_action :save_login_state, :only => [:create, :new]

  def new
    render layout: false
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to "/#{user.username}", notice: "Welcome #{params[:username]}!"
    else
      flash.now.alert = "Invalid email or password"
      render 'new', layout: false
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before_action :permitted_user, only: [:show]
  
  def show
    # @user = User.find(params[:id])    
    # @user = User.find_by_username(params[:username])
    
    @user = params[:username] ? User.find_by_username(params[:username]) : User.find(params[:id])

    if @user && @user != current_user
      redirect_to root_path
    else
      @lists = @user.lists.all
      render "lists/index"
    end
  end
  
  def new
    @user = User.new
    render layout: false
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully, please log in"
      # flash[:color]= "valid"
      render 'sessions/new', layout: false
    else
      flash[:notice] = "Form is invalid"
      # flash[:color]= "invalid"
      render 'new', layout: false
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav" style="text-align:center">
  <% if current_user %>
    Logged in as <%= current_user.username %> | 
    <%= link_to "Log Out", log_out_path %> |
  <% else %>
    <%= link_to "Log In", log_in_path %> or 
    <%= link_to "Sign Up", sign_up_path %>
  <% end %>  
<%= link_to 'Your Lists', user_path(current_user) if current_user %>

<h1 style="text-align:center">Lists</h1>

<% flash.each do |name, msg| %>
  <h4 style="color:red"><%= content_tag :div, msg, id: "flash_#{name}" %></h4>
<% end %>


</div>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <h3>
    <%= @list.list_name.blank? ? "Create a new list:":"Edit your list:"%>
  </h3>
  <table>
    <tr>
      <th style="text-align:left">
        <%= f.label :list_name, @list.list_name.blank? ? 'Give your list a name:':'Change the name:' %>
      </th>
    </tr>
    <tr>
      <td>
        <%= f.text_field :list_name, size: 72, placeholder: 'List Name' %>
      </th> 
    </tr>
  </table>
  <br />
  <table>
    <tr>
      <th style="text-align:left">
        <%= f.label :notes, 'Add any special directions?' %>
      </th>
    </tr>
    <tr>
      <td>
        <%= f.text_area :notes, size: "52x4", placeholder: 'Special Directions' %>
      </td>
    </tr>
  </table>
  <h3>
    <%= @list.items.count == 0 ? "Add some items:":"Edit your items:"%>
  </h3>
  <div class="field">
    <table>
      <tr>
        <th style="text-align:left">
          <%= f.label :name, 'Item' %>
        </th>
        <th style="text-align:left">
          <%= f.label :quan, 'Quantity' %>
        </th>
        <th style="text-align:left">
          <%= f.label :notes %>
        </th>
      </tr>
      <%= f.fields_for :items do |item_fields| %>
      <tr>
        <%= render 'item_fields', f: item_fields %>
      </tr>
      <% end %>
    </div>
  </table>

  <p>
    <div class="actions">
      <%= f.submit %>
    </div>
  </p>
<% end %>

app/views/lists/_item_fields.html.erb
<td>
  <%= f.text_field :name, placeholder: 'item name' %>
</td>
<td>
  <%= f.text_field :quan, placeholder: 'quantity' %>
</td>
<td>
  <%= f.text_field :notes, size: 50, placeholder: 'notes' %>
</td>
<td>
  <%= f.check_box :_destroy %>
  <%= f.label "Remove Item" %>
</td>

app/views/lists/edit.html.erb
<%= render 'form' %>

app/views/lists/index.html.erb
<h3>Your Lists:</h3>

<table>
  <% @lists.each do |list| %>
  <tr>
    <td style="width:60%"><%= link_to list.list_name, list %></td>
    <td><%= button_to 'Edit', edit_list_path(list), method: :get %></td>
    <td><%= button_to 'Delete', list_path(list), method: :delete, data: { confirm: 'Are you sure you want to delete this list?' } %></td>
  </tr>
<% end %>
</table>

<br />
<br />

<%= button_to 'Create New List!', new_list_path, method: :get %>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/show.html.erb
======= for testing ==========
<h3>List Owner: <%= @list.user.username %></h3>
<h3><%= current_user.id %></h3>
======= end testing ==========


<h3><%= @list.list_name.capitalize %></h3>

<ol>
  <% @list.items.each do |item| %>
    <li><%= item.name.capitalize %>
      <%= " - #{item.quan.capitalize}" unless item.quan.blank? %>
      <%= " - #{item.notes.capitalize}" unless item.notes.blank? %>
    </li>
  <% end %>
</ol>

<br />

<% unless @list.notes.blank? %>
  <strong>Notes: </strong><br />
  <%= @list.notes.capitalize %>
<% end %>

<br />
<br />

<table>
  <tr>
    <td>
      <%= button_to 'Edit this list', edit_list_path, method: :get %>
    </td>
    <td>
      <%= button_to 'Delete List', @list , method: :delete, data: { confirm: 'Are you sure you want to remove this list?'} %>
    </td>
  </tr>
</table>


<h4>Send your list to someone!</h4>
<%= form_tag(@list, method: "patch") do %>
  <table>
    <tr>
      <td><%= label_tag :sender, "Your name:" %></td>
      <td><%= text_field_tag :sender, nil, placeholder: 'name' %></td>
    </tr>
    <tr>
      <td><%= label_tag :send_to_address, "Email to:" %></td>
      <td><%= text_field_tag :send_to_address, nil, placeholder: 'email' %></td>
    </tr>
    <tr>
      <td colspan="2" style="text-align:right"><%= submit_tag "Email List!" %></td>
    </tr>
  </table>
<% end %>

app/views/send_list/quick_send.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3><%= "#{@sender.capitalize} wants you to pick up the following:"%></h3>

    <p>
      <strong>List:  </strong><%= @list.list_name.capitalize %>
    </p>

    <ol>
      <% @list.items.each do |item| %>
      <li>
        <%= "#{item.name.capitalize}" %>
        <%= " - #{item.quan.capitalize}" if item.quan != "" %>
        <%= " - #{item.notes}" if item.notes != "" %>
      </li>
      <% end %>
    </ol>
  
    <p>
      <strong>Notes:</strong>
    </p>
    <p>
      <%= @list.notes %>
    </p>
  
  </body>
</html>

app/views/users/new.html.erb
<div style="text-align:center">
<br />
<h1>Sign Up for Lists</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="signup_errors">
      <ul style="list-style-type:none">
        <% for message in @user.errors.full_messages %>
          <li style="color:red"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>

<% end %>

<br />
<p>
  Already signed up? <%= link_to 'Log in', log_in_path %>
</p>


</div>